services:
  - type: web
    name: gestor-unidad
    env: java
    buildCommand: |
      apt-get update
      apt-get install -y maven
      ./mvnw clean package
    startCommand: "java -jar target/*.jar"
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
